# Custom Language File for Launcher Customizer

[ejs.app]
title = "JBShow - Serveur Communautaire"

[ejs.landing]
mediaGitHubURL = "https://github.com/Metaloul/JBShow-Launcher"
mediaTwitterURL = "twitter.com/JBS_Ibonek"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@JeanBaptisteShow"
mediaDiscordURL = "https://discord.gg/aQtFyQk"

[ejs.settings]
sourceGithubLink = "https://github.com/Metaloul/JBShow-Launcher"
supportLink = "https://github.com/Metaloul/JBShow-Launcher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR LE LAUNCHER DU JBSHOW"
welcomeDescription = "Les reptiliens sont partout maintenant et l'organisation secrète du KJB mène des expériences sur le monde. Nan je déconne c'est juste un serveur Minecraft (quoi que...) Vous l'attendiez, il est enfin de retour, le serveur du JBShow renaît de ses cendres. Le but de ce launcher est de vous permettre une installation rapide et très facile du modpack nécessaire pour rejoindre le serveur. Aucun autre support (curseforge/modrinth...) ne sera pris en charge pour des raisons de praticité. Le serveur est en version alpha, vous en conviendrez que des bugs pourront survenir durant vos sessions de jeux. Si jamais vous en avez, merci de nous les report (en faisant attention de vérifier que personne n'en a déjà parlé bien-sûr)."
welcomeDescCTA = "Tu n'as qu'à cliquer sur continuer jeune maçon"